version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80  
    depends_on: 
      - phpfpm
  phpfpm:
    volumes:
        - ./static/:/usr/share/nginx/html/
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - 9000:9000
      