- hosts: all
  tasks:
  - name: install packages
    yum: 
      name:
      - bind
      - bind-utils
      - ntp
      state: present
  - name: copy transferkey
    copy: 
      src: provisioning/named.zonetransfer.key 
      dest: /etc/named.zonetransfer.key 
      owner: root
      group: named 
      mode: 0644
  - name: setup selinux
    shell: semanage fcontext -a -e /var/named /etc/named && restorecon -R -v /etc/named && setsebool -P named_write_master_zones 1

- hosts: nss
  tasks:  
  - name: copy resolv.conf
    copy: 
      src: servers-resolv.conf 
      dest: /etc/resolv.conf 
      owner: root 
      group: root
      mode: 0644      
  - name: set permissions
    file: 
      path: /etc/named
      owner: root
      group: named
      mode: 0670  
  - name: enable named
    service: 
      name: named
      enabled: yes
      state: restarted       

- hosts: clients
  tasks:  
  - name: copy resolv.conf
    copy: 
      src: clients-resolv.conf 
      dest: /etc/resolv.conf 
      owner: root 
      group: root
      mode: 0644
  - name: copy rndc
    copy:
      src: rndc.conf
      dest: /home/vagrant/rndc.conf
      owner: vagrant
      group: vagrant
      mode: 0644
  - name: copy motd
    copy: 
      src: client-motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644      

- hosts: ns01
  tasks:
  - name: copy named.conf
    copy: 
      src: provisioning/master-named.conf 
      dest: /etc/named.conf 
      owner: root
      group: named 
      mode: 0640
  - name: copy zones
    copy: src={{ item }} dest=/etc/named/ owner=root group=named mode=0660
    with_fileglob:
      - named.d*
      - named.n*

- hosts: ns02  
  tasks:
  - name: copy named.conf
    copy: 
      src: slave-named.conf
      dest: /etc/named.conf 
      owner: root
      group: named
      mode: 0640