# -*- mode: ruby -*-
# vim: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.provision "shell", inline: <<-SHELL
  cp /vagrant/script.sh /etc/cron.hourly/
  yum install sendmail –y
SHELL
end

